# Generated by Django 5.2.8 on 2026-07-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
